[package]
name = "p_swap_showdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
rand = "0.8.4"
pixels = "0.9.0"
